### ISSUE TITLE
How to change the width of column

### ISSUE THREAD

**Issue by supertorpez** [endsound0211/es-ng6-bs4-table#2]
Hi,
I have one table the same as the example you put, but i need to change the width of one column, or limit the text, to appear in various lines in the same file and column. example
Now appear 
"----------------------------------------------------------"
 lorem ipsum dolor sit amet, consectetur adipiscing elit. |
"----------------------------------------------------------"
and I want to appear thus
"------------------------------"
 lorem ipsum dolor sit amet, |
consectetur adipiscing elit.    |
"------------------------------"

Thanks and regards.

**Comment by HugoJBello** [comment]
Same issue here. If the text inside a record of a line is too big it seems impossible to change the style so that the text wraps.

**Comment by endsound0211** [comment]
I will automatically add class to th and td and let u add your own class on column. Then u can use ':ng-deep .someclass{}' to customize style.

**Comment by HugoJBello** [comment]
Hey, good idea, I just wanted to add avoid the rows to overflow so I added
```
::ng-deep td{
max-width: 150px; overflow-wrap: break-word;
}
```

**Comment by endsound0211** [comment]
I have published about default and customize class, version 1.6.0.
Now, every columns of th and td be added 'th-{{field}}' and 'td-{{field}}' to its class. The {{field}} is what you assign in es-ng-table-col
And you can set [classArray] to add classes, like <es-ng-table-col [classArray]="['class1', 'class2']">.

Last. use :ng-deep to customize style.

**Comment by HugoJBello** [comment]
Thanks for the fix ! Keep up the good work.
